name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Define your inputs here.
inputs:
  who-to-greet:
    description: Your input description here
    required: true
    default: World

# Define your outputs here.
outputs:
  greeting:
    description: Your output description here

# Update the image repository and tag below.
runs:
  using: docker
  image: docker://ghcr.io/actions/container-prebuilt-action:latest
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
